version: "3.3"

services:
  db:
    image: mariadb
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build: .
    container_name: wordpress-fab
    depends_on:
      - db
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./config/.htaccess:/var/www/html/.htaccess
      - ./config/wp-config.php:/var/www/html/wp-config.php
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      #WORDPRESS_DB_NAME: svevatrans
      WORDPRESS_DB_NAME: bustepaga
      #WORDPRESS_DB_NAME: wordpress
      PHP_EXTENSION_XDEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-wp
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: somewordpress
      UPLOAD_LIMIT: 300M
volumes:
  db_data: {}
